apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://user:change-me@postgres.healthcare-api.svc.cluster.local:5432/healthcare"
  DOCUMENT_STORAGE_ACCESS_KEY: "minioadmin"
  DOCUMENT_STORAGE_SECRET_KEY: "minioadmin"
  OPENAI_API_KEY: ""
